kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nodejs-ex
  namespace: new-app-apps
  labels:
    app: nodejs-ex
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-ex:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:14-ubi7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/sclorg/nodejs-ex'
    contextDir:   
  runPolicy: Serial