kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodejs-ex
  namespace: sbose
  labels:
    app: nodejs-ex
    app.kubernetes.io/component: nodejs-ex
    app.kubernetes.io/instance: nodejs-ex
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: nodejs-ex-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7 