apiVersion: v1
kind: Namespace
metadata:
  name: openshift-metering
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-argocd
  namespace: openshift-metering
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: openshift-metering
spec:
  targetNamespaces:
  - openshift-metering
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-workspaces
  namespace: openshift-metering
spec:
  channel: 4.7
  name: metering-ocp
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: crwoperator.v2.6.0ss